language: python
python:
  - "3.8"
 
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - python insert_word.py --input_file words.txt
  - python generate_tfrecord.py